version: 0.2
env:
  variables:
    DIST_FOLDER: "dist"
    BUILD_ENV: "dev"
    APP_DIR: "src"
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - cd $APP_DIR
      - echo "Install requirements"
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Doing a SAM translation on sample.yaml"
      - echo "The package command will put the Lambda function code into S3"
      - echo "It will then create a new version of the template file with the S3 url to the source code"
      - echo "Learn more at https://docs.aws.amazon.com/lambda/latest/dg/serverless_app.html"
      - aws cloudformation package --template-file sample.yaml --output-template-file sample-transformed.yaml --s3-bucket $SAM_BUCKET
      - |-
        echo "{ \"Parameters\" : { \"Stage\" : \"dev\", \"AppName\" : \"$APP_NAME\" } }" > sample-configuration-dev.json
        echo "{ \"Parameters\" : { \"Stage\" : \"test\", \"AppName\" : \"$APP_NAME\" } }" > sample-configuration-test.json
        echo "{ \"Parameters\" : { \"Stage\" : \"qa1\", \"AppName\" : \"$APP_NAME\" } }" > sample-configuration-qa1.json
        echo "{ \"Parameters\" : { \"Stage\" : \"qa2\", \"AppName\" : \"$APP_NAME\" } }" > sample-configuration-qa2.json
        echo "{ \"Parameters\" : { \"Stage\" : \"prod\", \"AppName\" : \"$APP_NAME\" } }" > sample-configuration-prod.json
      - ls -hal
artifacts:
  base-directory: $APP_DIR
  files:
    - env/*
    - sample-transformed.yaml
    - sample-configuration-dev.json
    - sample-configuration-test.json
    - sample-configuration-qa1.json
    - sample-configuration-qa2.json
    - sample-configuration-prod.json
