AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Environment
    Type: String
  AppName:
    Description: Application name
    Type: String

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub LambdaRole-${AWS::Region}-${AppName}-${Stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole

  SampleApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/sample.lambda_handler
      Runtime: python3.7
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref SampleDDbTable
      Events:
        GetTableData:
          Type: Api
          Properties:
            Path: /sample/{id}
            Method: get
        PostTableData:
          Type: Api
          Properties:
            Path: /sample/{id}
            Method: post
        DeleteTableData:
          Type: Api
          Properties:
            Path: /sample/{id}
            Method: delete
      Role: !GetAtt [LambdaRole, Arn]
      Tags:
        Sample: true

  SampleApiFunctionPermission:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub SampleApiFunctionPermission-${AWS::Region}-${AWS::AccountId}-${SampleApiFunction}
      Roles:
        - !Ref LambdaRole
      PolicyDocument:
        Version: '2012-10-17' # Policy Document
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SampleDDbTable}
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${SampleApiFunction}:*

  SampleDDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub sample-table-${AWS::StackName}
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        Sample: true

Outputs:
  SampleApiUrl:
    Value: !Sub ${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}
    Description: API Gateway URL that triggers your Lambda
  SampleTableName:
    Value: !Ref SampleDDbTable
    Description: DynamoDB Table name that is passed into the Lambda environment variables
